# C3D entity placement v1
[entities]
format=C3D-ENTITIES-1

[entity.0]
x=1056
z=3616
angle=0
type=1
param=0

[entity.1]
x=1008
z=3600
angle=0
type=2
param=0

[entity.2]
x=1104
z=3600
angle=0
type=3
param=0

[entity.3]
x=960
z=3600
angle=0
type=4
param=0
